version: "3.9"

name: veterinary-clinic

services:
  rabbitmq:
    image: masstransit/rabbitmq:3.9.7
    container_name: rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    expose:
      - 5672:5672
      - 15672:15672
    networks:
      vc-network:
        ipv4_address: 77.0.0.1
    restart: on-failure

  samba:
    build:
      context: .
      dockerfile: ./_docker/samba/Dockerfile
    image: samba
    container_name: samba
    expose:
      - 139:139/tcp
      - 445:445/tcp
    ports:
      - 1390:139/tcp
      - 4450:445/tcp
    networks:
      vc-network:
        ipv4_address: 77.0.0.2
    volumes:
      - ./_docker/samba/storage/:/storage
    stdin_open: true
    tty: true

networks:
  vc-network:
    name: vc-network
    driver: bridge
    ipam:
      config:
        - subnet: 77.0.0.0/16
          gateway: 77.0.0.254
