version: "3.9"

name: veterinary-clinic

services:
  rabbitmq:
    image: masstransit/rabbitmq:3.9.7
    container_name: rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    expose:
      - 5672:5672
      - 15672:15672
    networks:
      vc-network:
        ipv4_address: 77.0.0.1
    restart: on-failure

  samba:
    build:
      context: .
      dockerfile: ./_docker/samba/Dockerfile
    image: samba
    container_name: samba
    expose:
      - 139:139/tcp
      - 445:445/tcp
    ports:
      - 1390:139/tcp
      - 4450:445/tcp
    networks:
      vc-network:
        ipv4_address: 77.0.0.2
    volumes:
      - ./_docker/samba/storage/:/storage
    stdin_open: true
    tty: true

  public-web:
    build:
      context: .
      dockerfile: ./Public/src/Fnunez.VeterinaryClinic.Public.Web/Dockerfile
    image: public-web
    container_name: public-web
    environment:
      - ASPNETCORE_ENVIRONMENT=DockerDevelopment
      - ASPNETCORE_URLS=https://+:7138
      - ASPNETCORE_HTTPS_PORT=7138
      - ASPNETCORE_Kestrel__Certificates__Default__Password=VeterinaryClinic123!
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/veterinaryclinic.pfx
      - VIRTUAL_HOST=public-web.vc.local
    expose:
      - 7138:7138
    ports:
      - 7138:7138
    networks:
      vc-network:
        ipv4_address: 77.0.0.3
    restart: on-failure
    depends_on:
      - rabbitmq
    volumes:
      - ./_docker/certs/veterinaryclinic.pfx:/https/veterinaryclinic.pfx:ro
      - ./_docker/certs/veterinaryclinic.crt:/usr/local/share/ca-certificates/veterinaryclinic.crt:ro
    entrypoint: /bin/sh -c "update-ca-certificates && dotnet Fnunez.VeterinaryClinic.Public.Web.dll"

networks:
  vc-network:
    name: vc-network
    driver: bridge
    ipam:
      config:
        - subnet: 77.0.0.0/16
          gateway: 77.0.0.254

volumes:
  samba-volume:
    driver: local
    driver_opts:
      type: cifs
      device: //77.0.0.2/storage
      o: "username=guest,password=guest,vers=3.0"
