version: "3.9"

name: veterinary-clinic

services:
  rabbitmq:
    image: masstransit/rabbitmq:3.9.7
    container_name: rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    expose:
      - 5672:5672
      - 15672:15672
    networks:
      vc-network:
        ipv4_address: 77.0.0.1
    restart: on-failure

  samba:
    build:
      context: .
      dockerfile: ./_docker/samba/Dockerfile
    image: samba
    container_name: samba
    expose:
      - 139:139/tcp
      - 445:445/tcp
    ports:
      - 1390:139/tcp
      - 4450:445/tcp
    networks:
      vc-network:
        ipv4_address: 77.0.0.2
    volumes:
      - ./_docker/samba/storage/:/storage
    stdin_open: true
    tty: true

  public-web:
    build:
      context: .
      dockerfile: ./Public/src/Fnunez.VeterinaryClinic.Public.Web/Dockerfile
    image: public-web
    container_name: public-web
    environment:
      - ASPNETCORE_ENVIRONMENT=DockerDevelopment
      - ASPNETCORE_URLS=https://+:7138
      - ASPNETCORE_HTTPS_PORT=7138
      - ASPNETCORE_Kestrel__Certificates__Default__Password=VeterinaryClinic123!
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/veterinaryclinic.pfx
      - VIRTUAL_HOST=public-web.vc.local
    expose:
      - 7138:7138
    ports:
      - 7138:7138
    networks:
      vc-network:
        ipv4_address: 77.0.0.3
    restart: on-failure
    depends_on:
      - rabbitmq
    volumes:
      - ./_docker/certs/veterinaryclinic.pfx:/https/veterinaryclinic.pfx:ro
      - ./_docker/certs/veterinaryclinic.crt:/usr/local/share/ca-certificates/veterinaryclinic.crt:ro
    entrypoint: /bin/sh -c "update-ca-certificates && dotnet Fnunez.VeterinaryClinic.Public.Web.dll"

  identity-db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: identity-db
    environment:
      ACCEPT_EULA: "Y"
      MSSQL_PID: "Developer"
      MSSQL_SA_PASSWORD: "VeterinaryClinic123!"
    expose:
      - 14330:1433
    ports:
      - 14330:1433
    networks:
      vc-network:
        ipv4_address: 77.0.0.4
    restart: on-failure

  identity-api:
    build:
      context: .
      dockerfile: ./Identity/src/Presentation/Fnunez.VeterinaryClinic.Identity.Api/Dockerfile
    image: identity-api
    container_name: identity-api.vc.local
    environment:
      - ASPNETCORE_ENVIRONMENT=DockerDevelopment
      - ASPNETCORE_URLS=https://+:7066
      - ASPNETCORE_HTTPS_PORT=7066
      - ASPNETCORE_Kestrel__Certificates__Default__Password=VeterinaryClinic123!
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/veterinaryclinic.pfx
      - VIRTUAL_HOST=identity-api.vc.local
    expose:
      - 7066:7066
    ports:
      - 7066:7066
    networks:
      vc-network:
        ipv4_address: 77.0.0.5
    restart: on-failure
    depends_on:
      - identity-db
    volumes:
      - ./_docker/certs/veterinaryclinic.pfx:/https/veterinaryclinic.pfx:ro
      - ./_docker/certs/veterinaryclinic.crt:/usr/local/share/ca-certificates/veterinaryclinic.crt:ro
    entrypoint: /bin/sh -c "update-ca-certificates && dotnet Fnunez.VeterinaryClinic.Identity.Api.dll"

  clinicmanagement-db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: clinicmanagement-db
    environment:
      ACCEPT_EULA: "Y"
      MSSQL_PID: "Developer"
      MSSQL_SA_PASSWORD: "VeterinaryClinic123!"
    expose:
      - 14331:1433
    ports:
      - 14331:1433
    networks:
      vc-network:
        ipv4_address: 77.0.0.6
    restart: on-failure

  clinicmanagement-api:
    build:
      context: .
      dockerfile: ./ClinicManagement/src/Presentation/Fnunez.VeterinaryClinic.ClinicManagement.Api/Dockerfile
    image: clinicmanagement-api
    container_name: clinicmanagement-api
    environment:
      - ASPNETCORE_ENVIRONMENT=DockerDevelopment
      - ASPNETCORE_URLS=https://+:7229
      - ASPNETCORE_HTTPS_PORT=7229
      - ASPNETCORE_Kestrel__Certificates__Default__Password=VeterinaryClinic123!
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/veterinaryclinic.pfx
    expose:
      - 7229:7229
    networks:
      vc-network:
        ipv4_address: 77.0.0.7
    restart: on-failure
    depends_on:
      - clinicmanagement-db
      - samba
      - rabbitmq
    volumes:
      - ./_docker/certs/veterinaryclinic.pfx:/https/veterinaryclinic.pfx:ro
      - ./_docker/certs/veterinaryclinic.crt:/usr/local/share/ca-certificates/veterinaryclinic.crt:ro
      - samba-volume:/storage
    entrypoint: /bin/sh -c "sleep 20 && update-ca-certificates && dotnet Fnunez.VeterinaryClinic.ClinicManagement.Api.dll"

  clinicmanagement-blazor:
    build:
      context: .
      dockerfile: ./ClinicManagement/src/Presentation/BlazorClient/Fnunez.VeterinaryClinic.ClinicManagement.BlazorClient.Server/Dockerfile
    image: clinicmanagement-blazor
    container_name: clinicmanagement-blazor
    environment:
      # Forced to stay as Development environment coz Duende BFF license
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:7004
      - ASPNETCORE_HTTPS_PORT=7004
      - ASPNETCORE_Kestrel__Certificates__Default__Password=VeterinaryClinic123!
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/veterinaryclinic.pfx
      - VIRTUAL_HOST=clinicmanagement-blazor.vc.local
    expose:
      - 7004:7004
    ports:
      - 7004:7004
    networks:
      vc-network:
        ipv4_address: 77.0.0.8
    restart: on-failure
    depends_on:
      - clinicmanagement-api
      - identity-api
      - rabbitmq
    volumes:
      - ./_docker/certs/veterinaryclinic.pfx:/https/veterinaryclinic.pfx:ro
      - ./_docker/certs/veterinaryclinic.crt:/usr/local/share/ca-certificates/veterinaryclinic.crt:ro
    entrypoint: /bin/sh -c "update-ca-certificates && dotnet Fnunez.VeterinaryClinic.ClinicManagement.BlazorClient.Server.dll"

  clinicmanagementnotifications-db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: clinicmanagementnotifications-db
    environment:
      ACCEPT_EULA: "Y"
      MSSQL_PID: "Developer"
      MSSQL_SA_PASSWORD: "VeterinaryClinic123!"
    expose:
      - 14332:1433
    ports:
      - 14332:1433
    networks:
      vc-network:
        ipv4_address: 77.0.0.9
    restart: on-failure

  clinicmanagementnotifications-api:
    build:
      context: .
      dockerfile: ./ClinicManagementN/src/Presentation/Fnunez.VeterinaryClinic.ClinicManagementNotifications.Api/Dockerfile
    image: clinicmanagementnotifications-api
    container_name: clinicmanagementnotifications-api
    environment:
      - ASPNETCORE_ENVIRONMENT=DockerDevelopment
      - ASPNETCORE_URLS=https://+:7082
      - ASPNETCORE_HTTPS_PORT=7082
      - ASPNETCORE_Kestrel__Certificates__Default__Password=VeterinaryClinic123!
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/veterinaryclinic.pfx
    expose:
      - 7082:7082
    networks:
      vc-network:
        ipv4_address: 77.0.0.10
    restart: on-failure
    depends_on:
      - clinicmanagementnotifications-db
      - identity-api
      - rabbitmq
    volumes:
      - ./_docker/certs/veterinaryclinic.pfx:/https/veterinaryclinic.pfx:ro
      - ./_docker/certs/veterinaryclinic.crt:/usr/local/share/ca-certificates/veterinaryclinic.crt:ro
    entrypoint: /bin/sh -c "update-ca-certificates && dotnet Fnunez.VeterinaryClinic.ClinicManagementNotifications.Api.dll"

  scheduling-db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: scheduling-db
    environment:
      ACCEPT_EULA: "Y"
      MSSQL_PID: "Developer"
      MSSQL_SA_PASSWORD: "VeterinaryClinic123!"
    expose:
      - 14333:1433
    ports:
      - 14333:1433
    networks:
      vc-network:
        ipv4_address: 77.0.0.11
    restart: on-failure

  scheduling-api:
    build:
      context: .
      dockerfile: ./Scheduling/src/Presentation/Fnunez.VeterinaryClinic.Scheduling.Api/Dockerfile
    image: scheduling-api
    container_name: scheduling-api
    environment:
      - ASPNETCORE_ENVIRONMENT=DockerDevelopment
      - ASPNETCORE_URLS=https://+:7266
      - ASPNETCORE_HTTPS_PORT=7266
      - ASPNETCORE_Kestrel__Certificates__Default__Password=VeterinaryClinic123!
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/veterinaryclinic.pfx
    expose:
      - 7266:7266
    networks:
      vc-network:
        ipv4_address: 77.0.0.12
    restart: on-failure
    depends_on:
      - clinicmanagement-api
      - samba
      - scheduling-db
      - rabbitmq
    volumes:
      - ./_docker/certs/veterinaryclinic.pfx:/https/veterinaryclinic.pfx:ro
      - ./_docker/certs/veterinaryclinic.crt:/usr/local/share/ca-certificates/veterinaryclinic.crt:ro
      - samba-volume:/storage
    entrypoint: /bin/sh -c "update-ca-certificates && dotnet Fnunez.VeterinaryClinic.Scheduling.Api.dll"

  scheduling-blazor:
    build:
      context: .
      dockerfile: ./Scheduling/src/Presentation/BlazorClient/Fnunez.VeterinaryClinic.Scheduling.BlazorClient.Server/Dockerfile
    image: scheduling-blazor
    container_name: scheduling-blazor
    environment:
      # Required to stay as Development environment coz Duende BFF license
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:7154
      - ASPNETCORE_HTTPS_PORT=7154
      - ASPNETCORE_Kestrel__Certificates__Default__Password=VeterinaryClinic123!
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/veterinaryclinic.pfx
      - VIRTUAL_HOST=scheduling-blazor.vc.local
    expose:
      - 7154:7154
    ports:
      - 7154:7154
    networks:
      vc-network:
        ipv4_address: 77.0.0.13
    restart: on-failure
    depends_on:
      - scheduling-api
      - identity-api
      - rabbitmq
    volumes:
      - ./_docker/certs/veterinaryclinic.pfx:/https/veterinaryclinic.pfx:ro
      - ./_docker/certs/veterinaryclinic.crt:/usr/local/share/ca-certificates/veterinaryclinic.crt:ro
    entrypoint: /bin/sh -c "update-ca-certificates && dotnet Fnunez.VeterinaryClinic.Scheduling.BlazorClient.Server.dll"

  schedulingnotifications-db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: schedulingnotifications-db
    environment:
      ACCEPT_EULA: "Y"
      MSSQL_PID: "Developer"
      MSSQL_SA_PASSWORD: "VeterinaryClinic123!"
    expose:
      - 14334:1433
    ports:
      - 14334:1433
    networks:
      vc-network:
        ipv4_address: 77.0.0.14
    restart: on-failure

networks:
  vc-network:
    name: vc-network
    driver: bridge
    ipam:
      config:
        - subnet: 77.0.0.0/16
          gateway: 77.0.0.254

volumes:
  samba-volume:
    driver: local
    driver_opts:
      type: cifs
      device: //77.0.0.2/storage
      o: "username=guest,password=guest,vers=3.0"
