version: "3.9"

name: veterinary-clinic

services:
  rabbitmq:
    image: masstransit/rabbitmq:3.9.7
    container_name: rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    expose:
      - 5672:5672
      - 15672:15672
    restart: always
