using Fnunez.VeterinaryClinic.Scheduling.Application.Services.IntegrationEventReceiver.IntegrationEvents;
using MediatR;

namespace Fnunez.VeterinaryClinic.Scheduling.Application.Features.Patients.ReceiveIntegrationEvents.PatientCreated;

public record PatientCreatedReceiveIntegrationEvent(PatientCreatedIntegrationEvent PatientCreatedIntegrationEvent)
    : INotification;