using Fnunez.VeterinaryClinic.ClinicManagement.Application.SharedModel.Patient.GetPatientsFilterClient;
using MediatR;

namespace Fnunez.VeterinaryClinic.ClinicManagement.Application.Features.Patients.Queries.GetPatientsFilterClient;

public record GetPatientsFilterClientQuery(GetPatientsFilterClientRequest GetPatientsFilterClientRequest)
    : IRequest<GetPatientsFilterClientResponse>;