using Fnunez.VeterinaryClinic.Scheduling.Application.Services.IntegrationEventReceiver.IntegrationEvents;
using MediatR;

namespace Fnunez.VeterinaryClinic.Scheduling.Application.Features.Patients.ReceiveIntegrationEvents.PatientUpdated;

public record PatientUpdatedReceiveIntegrationEvent(PatientUpdatedIntegrationEvent PatientUpdatedIntegrationEvent)
    : INotification;