using Fnunez.VeterinaryClinic.Scheduling.Application.Services.IntegrationEventReceiver.IntegrationEvents;
using MediatR;

namespace Fnunez.VeterinaryClinic.Scheduling.Application.Features.AppointmentTypes.ReceiveIntegrationEvents.AppointmentTypeUpdated;

public record AppointmentTypeUpdatedReceiveIntegrationEvent(AppointmentTypeUpdatedIntegrationEvent AppointmentTypeUpdatedIntegrationEvent)
    : INotification;