using Fnunez.VeterinaryClinic.Scheduling.Application.SharedModel.Appointment.GetAppointmentsFilterDoctor;
using MediatR;

namespace Fnunez.VeterinaryClinic.Scheduling.Application.Features.Appointments.Queries.GetAppointmentsFilterDoctor;

public record GetAppointmentsFilterDoctorQuery(GetAppointmentsFilterDoctorRequest GetAppointmentsFilterDoctorRequest)
    : IRequest<GetAppointmentsFilterDoctorResponse>;