using Fnunez.VeterinaryClinic.Scheduling.Application.Services.IntegrationEventReceiver.IntegrationEvents;
using MediatR;

namespace Fnunez.VeterinaryClinic.Scheduling.Application.Features.Clinics.ReceiveIntegrationEvents.ClinicUpdated;

public record ClinicUpdatedReceiveIntegrationEvent(ClinicUpdatedIntegrationEvent ClinicUpdatedIntegrationEvent)
    : INotification;