using Fnunez.VeterinaryClinic.Scheduling.Application.SharedModel.Client.GetClientsFilterEmailAddress;
using MediatR;

namespace Fnunez.VeterinaryClinic.Scheduling.Application.Features.Clients.Queries.GetClientsFilterEmailAddress;

public record GetClientsFilterEmailAddressQuery(GetClientsFilterEmailAddressRequest GetClientsFilterEmailAddressRequest)
    : IRequest<GetClientsFilterEmailAddressResponse>;