using Contracts;
using MediatR;

namespace Fnunez.VeterinaryClinic.ClinicManagement.Application.Features.AppointmentTypes.SendIntegrationEvents.AppointmentTypeUpdated;

public record AppointmentTypeUpdatedSendIntegrationEvent(AppointmentTypeUpdatedIntegrationEventContract AppointmentTypeUpdatedIntegrationEventContract)
    : INotification;